feat: add support to custom base URL and models
TheFireCo/genkit-plugins pull request #143
Opened 2024-09-06 22:47 UTC by MagdielCAS

**This pull request is related to:**

- [ ] A bug
- [ ] A new feature
- [ ] Documentation
- [x] Enhancement

**I have checked the following:**

- [x] I have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md);
- [ ] I have added new tests (for bug fixes/features);
- [ ] I have added/updated the documentation (for bug fixes / features).

**Description:**
This Pull Request adds support for custom Base URL and custom models for the OpenAI client. With tools like LiteLLM, and LLM providers like OpenRouter that offers a great variety of models under the OpenAI API Specification, we support private and custom LLMs with the same plugin.

**Related issues:**
Please, link the related issues that this pull request will resolve here (if any).

This Resolves #56

2024-10-23 14:15 UTC, ehelbig1 approved these changes

2024-11-19 10:45 UTC, xavidop requested changes
update code with 0.9

2024-11-19 10:45 UTC, xavidop requested changes

2024-11-19 10:45 UTC, xavidop commented on plugins/openai/src/index.ts
> +    const baseURL = options?.baseURL || process.env.OPENAI_BASE_URL;
we should set one by default if both are empty

2025-02-14 08:56 UTC, xavidop commented
this has been included already

2025-02-14 08:56 UTC, closed without merging