deps!: migrate plugins to 0.9 RC
TheFireCo/genkit-plugins pull request #155
Opened 2024-11-01 15:31 UTC by cabljac

_Before you submit a pull request, please make sure you have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md)._

**This pull request is related to:**

- [ ] A bug
- [ ] A new feature
- [ ] Documentation
- [x] Other: The `next` version of Genkit (0.9) has many breaking changes for the plugin API. This PR migrates some 3P plugins to an RC of `0.9`.

**I have checked the following:**

- [x] I have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md);
- [x] I have added new tests (for bug fixes/features);
- [ ] I have added/updated the documentation (for bug fixes / features).

**Description:**
Migrate several 3P plugins to `0.9`
**Related issues:**
https://github.com/firebase/genkit/issues/1088

2024-11-01 16:40 UTC, pavelgj commented on examples/anthropic/package.json
> +    "genkit": "^0.9.0-dev.2",
```suggestion
    "genkit": "^0.9.0-dev.2 | ^0.9",
```

2024-11-11 12:45 UTC, cabljac commented on plugins/anthropic/src/claude.ts
> +        )}.`
Not within scope of PR

2024-11-11 12:46 UTC, cabljac commented on plugins/anthropic/src/claude.ts
> +    )}.`
Not within scope of PR

2024-11-11 12:46 UTC, cabljac commented on plugins/cohere/package.json
> +    "cohere-ai": "^7.9.5"
genkit now re-exports {z} from zod

2024-11-11 12:50 UTC, cabljac commented on package.json
>    }
This was added in to prevent an error in one of the plugins.

2024-11-11 12:50 UTC, xavidop approved these changes
LGTM

2024-11-11 12:53 UTC, cabljac commented on plugins/cohere/src/command.ts
>        ])
This is a fair point, will look into this and resolve

2024-11-11 12:53 UTC, cabljac commented on plugins/cohere/src/index.ts
> +  });
out of scope

2024-11-11 12:54 UTC, cabljac commented on plugins/groq/src/groq_models.ts
> +  name: 'groq/mixtral-8x7b',
good catch, will investigate

2024-11-11 12:55 UTC, cabljac commented on plugins/groq/src/groq_models.ts
> +  name: 'groq/mixtral-8x7b',
this potential bug is out of scope of the PR as it exists already in the code

2024-11-11 12:56 UTC, cabljac commented on plugins/mistral/src/index.ts
> +
out of scope of PR

2024-11-11 12:57 UTC, cabljac commented on plugins/mistral/src/mistral_llms.ts
> +    versions: ['mistral-medium-231'],
out of scope

2024-11-11 12:57 UTC, cabljac commented on plugins/mistral/src/mistral_llms.ts
> +    // @ts-ignore
Out of scope of this PR; preexisting.

2024-11-11 12:57 UTC, xavidop requested changes
the readme of each plugin needs to be updated

2024-11-11 12:58 UTC, cabljac commented on plugins/openai/src/dalle.ts
> +    prompt: new Message(request.messages[0]).text,
out of scope, azure-openai is not fully implemented

2024-11-11 13:00 UTC, cabljac commented on plugins/mistral/src/embedders.ts
>        });
out of scope

2024-11-11 18:11 UTC, pavelgj commented on examples/anthropic/package.json
> +    "genkit": "^0.9.0-dev.2",
```suggestion
    "genkit": "^0.9.0-dev | ^0.9.0-rc | ^0.9",
```

2024-11-12 18:20 UTC, pavelgj approved these changes

2024-11-13 08:58 UTC, davidoort reviewed
I see a bunch of files being deleted (e.g. prompt files, README, .env.local) would be helpful to understand the reasoning behind this. Are they just incompatible or they've been moved somewhere else?

2024-11-13 13:01 UTC, pavelgj commented on package.json
> +    "genkit": "^0.9.0-dev.2",
This needs to cover ^0.9

2024-11-13 14:07 UTC, pavelgj commented on examples/cohere/package.json
> +    "genkit": "^0.9.0-dev.2",
```suggestion
    "genkit": "^0.9.0-rc || ^0.9",
```

2024-11-13 14:09 UTC, pavelgj commented on examples/groq/package.json
> +    "genkit": "^0.9.0-dev.2",
```suggestion
    "genkit": "^0.9.0-rc || ^0.9",
```

2024-11-13 14:09 UTC, pavelgj commented on examples/mistral/package.json
> +    "genkit": "^0.9.0-dev.2",
```suggestion
    "genkit": "^0.9.0-rc || ^0.9",
```

2024-11-13 14:10 UTC, pavelgj commented on examples/openai/package.json
> +    "genkit": "^0.9.0-dev.2",
```suggestion
    "genkit": "^0.9.0-rc || ^0.9",
```

2024-11-13 14:10 UTC, pavelgj commented on package.json
> +    "genkit": "^0.9.0-dev.2",
```suggestion
    "genkit": "^0.9.0-rc || ^0.9",
```

2024-11-13 14:11 UTC, pavelgj commented on plugins/anthropic/package.json
> +    "genkit": ">=0.9.0-dev.2 <1.0.0 || ^0.9"
```suggestion
    "genkit": "~0.9.0-rc || ^0.9"
```

2024-11-13 14:12 UTC, pavelgj commented on plugins/cohere/package.json
> +    "genkit": ">=0.9.0-dev.2 <1.0.0 || ^0.9"
```suggestion
    "genkit": "^0.9.0-rc || ^0.9"
```

2024-11-13 14:12 UTC, pavelgj commented on plugins/groq/package.json
> +    "genkit": ">=0.9.0-dev.2 <1.0.0 || ^0.9"
```suggestion
    "genkit": "^0.9.0-rc || ^0.9"
```

2024-11-13 14:12 UTC, pavelgj commented on plugins/mistral/package.json
> +    "genkit": ">=0.9.0-dev.2 <1.0.0 || ^0.9"
```suggestion
    "genkit": "^0.9.0-rc || ^0.9"
```

2024-11-13 14:12 UTC, pavelgj commented on plugins/openai/package.json
> +    "genkit": ">=0.9.0-dev.2 <1.0.0 || ^0.9"
```suggestion
    "genkit": "^0.9.0-rc || ^0.9"
```

2024-11-13 14:18 UTC, pavelgj commented
> I see a bunch of files being deleted (e.g. prompt files, README, .env.local) would be helpful to understand the reasoning behind this. Are they just incompatible or they've been moved somewhere else?

It appears the prompt files were unused, so were deleted. More samples were added (per plugin). Perhaps some tool calling samples did not survive the move... @cabljac could you please take a look?

2024-11-13 15:32 UTC, cabljac commented
> > I see a bunch of files being deleted (e.g. prompt files, README, .env.local) would be helpful to understand the reasoning behind this. Are they just incompatible or they've been moved somewhere else?
> 
> It appears the prompt files were unused, so were deleted. More samples were added (per plugin). Perhaps some tool calling samples did not survive the move... @cabljac could you please take a look?

Yeah they were unused and the example was fairly out of date, so i replaced it with new samples. I've push a change now to reinstate and update that original example code though :)

2024-11-14 00:53 UTC, pavelgj commented
Not to rush, but Genkit 0.9.0 is now released. It would be great if these plugins could be updated as soon as possible.

2024-11-14 07:35 UTC, davidoort submitted a review, later dismissed

2024-11-14 15:03 UTC, EPMatt commented
Hey @cabljac ,
thank you for your contribution. I've fixed build issues related to this PR - plus bumped the genkit version to `v0.9.0` stable.
As I don't have push access to this branch, I've uploaded the edits to a separate branch: https://github.com/TheFireCo/genkit-plugins/tree/pr/cabljac/155 and opened a PR on your fork.

2024-11-14 15:11 UTC, closed without merging