Add new plugin : Genkit HNSW
TheFireCo/genkit-plugins pull request #51
Opened 2024-05-23 19:08 UTC by retzd-tech

_Before you submit a pull request, please make sure you have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md)._

**This pull request is related to:**

- [ ] A bug
- [x] A new feature
- [x] Documentation
- [ ] Other (please specify)

**I have checked the following:**

- [x] I have read and understood the [contribution guidelines](https://github.com/TheFireCo/genkit-plugins/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/TheFireCo/genkit-plugins/blob/main/CODE_OF_CONDUCT.md);
- [x] I have added new tests (for bug fixes/features);
- [x] I have added/updated the documentation (for bug fixes / features).

**Description:**
Add a new plugin Genkit HNSW

2024-05-25 08:20 UTC, EPMatt commented
@retzd-tech thanks for the contribution! 🎉  Will review and check what's missing at some point today

2024-05-26 10:16 UTC, EPMatt requested changes
@retzd-tech thank you so much for your contribution! Fixed some dependencies issues here and there, now the build process completes successfully.

@davidoort I suggested some changes, tagging you in the comments. I'd suggest to take those steps before merging. Let me know if you need help.

Given the size of the PR, I advise to first merge this and publish the plugin, then work  on the other needed changes (Code Owners, docs, etc.) on a different PR.

2024-05-26 10:16 UTC, EPMatt commented on plugins/hnsw/LICENSE
@davidoort needs to be updated to The Fire Company license before publishing

2024-05-26 10:16 UTC, EPMatt commented on plugins/hnsw/README.md
@davidoort we should align this to our README template

2024-05-26 10:16 UTC, EPMatt commented on plugins/hnsw/coverage/clover.xml
I believe these coverage files do not need to be committed at all.

2024-05-26 10:16 UTC, EPMatt commented on plugins/hnsw/CONTRIBUTING.md
@davidoort the content of this file should be translated to GitHub issues so people can easily spot the missing contributions and help with that. 👍🏻

2024-05-26 10:16 UTC, EPMatt commented on plugins/hnsw/package.json
> +    "zod": "^3.22.4"
@davidoort I moved `@genkit-ai/ai` and `@genkit-ai/core` to peer dependencies, not sure if some of these need to be moved there as well. Maybe worth checking.

2024-05-26 10:16 UTC, EPMatt commented on plugins/hnsw/tsconfig.json
@davidoort let's also align this to the ones we are using on other plugins

2024-05-27 06:26 UTC, davidoort commented on plugins/hnsw/LICENSE
The other plugins don't have a license file so I'm removing it from this one as well

2024-05-27 06:33 UTC, davidoort commented on plugins/hnsw/CONTRIBUTING.md
This is a good idea for some of the other plugins!

2024-05-27 12:28 UTC, davidoort commented on plugins/hnsw/package.json
> +    "zod": "^3.22.4"
sounds good!

2024-05-28 16:18 UTC, davidoort commented on plugins/hnsw/CONTRIBUTING.md
this is a good idea, but not required for merging imo

2024-05-29 17:10 UTC, davidoort approved these changes
Thank you so so much for the contribution and addressing all comments @retzd-tech ! I'm so excited to get this released! 🎉🔥

2024-05-29 17:10 UTC, merged